ePizzaHub.WebUI/Areas/User/Controllers/OrderController.cs
using ePizzaHub.Repositories.Models;
using ePizzaHub.Services.Interfaces;
using ePizzaHub.WebUI.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ePizzaHub.WebUI.Areas.User.Controllers
{
    public class OrderController : BaseController
    {
        IOrderService _orderService;
        public OrderController(IOrderService orderService, IUserAccessor userAccessor)  :base(userAccessor)
        {
            _orderService = orderService;
        }
        public IActionResult Index()
        {
            var order = _orderService.GetUserOrders(CurrentUser.Id);
            return View(order);
        }

        [Route("~/User/Order/Details/{OrderId}")]
        public IActionResult Details(string OrderId)
        {
            OrderModel Order = _orderService.GetOrderDetails(OrderId);
            return View(Order);
        }
    }
}

ePizzaHub.WebUI/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ePizzaHub.WebUI.Helpers;
using ePizzaHub.Repositories.Models;
using ePizzaHub.WebUI.Models;
using ePizzaHub.Services.Interfaces;
using ePizzaHub.Services.Models;
using Microsoft.Extensions.Options;
using ePizzaHub.WebUI.Interfaces;
using ePizzaHub.entities;
using Microsoft.AspNetCore.Http;

namespace ePizzaHub.WebUI.Controllers
{
    public class PaymentController : BaseController
    {

        //key_id: rzp_test_oQiisRP0aJkxjQ
        //key_secret:n5Kg57NnQcZglJ6lWKaUiOG8

        //Master card : 5104 0600 0000 0008
        //Visa: 4111 1111 1111 1111

        private readonly IOptions<RazorPayConfig> _razorPayConfig;
        private readonly IPaymentService _paymentService;
        private readonly IOrderService _orderService;
        public PaymentController(IPaymentService paymentService, IOptions<RazorPayConfig> razorPayConfig, IUserAccessor userAccessor, IOrderService orderService) : base(userAccessor)
        {
            _razorPayConfig = razorPayConfig;
            _paymentService = paymentService;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            PaymentModel payment = new PaymentModel();
            CartModel cart = TempData.Peek<CartModel>("Cart");
            if (cart != null)
            {
                payment.Cart = cart;
            }
            payment.GrandTotal = Math.Round(cart.GrandTotal);
            payment.Currency = "INR";
            string items = "";
            foreach (var item in cart.Items)
            {
                items += item.Name + ",";
            }
            payment.Description = items;
            payment.RazorpayKey = _razorPayConfig.Value.Key;
            payment.Receipt = Guid.NewGuid().ToString();

            //flow in razor pay: need to create order first
            payment.OrderId = _paymentService.CreateOrder(payment.GrandTotal * 100, payment.Currency, payment.Receipt);

            return View(payment);
        }

        [HttpPost]
        public IActionResult Status(IFormCollection form)
        {
            try
            {
                if (form.Keys.Count > 0 && !String.IsNullOrWhiteSpace(form["rzp_paymentid"]))
                {
                    string paymentId = form["rzp_paymentid"];
                    string orderId = form["rzp_orderid"];
                    string signature = form["rzp_signature"];
                    string transactionId = form["Receipt"];
                    string currency = form["Currency"];

                    var payment = _paymentService.GetPaymentDetails(paymentId);
                    bool IsSignVerified = _paymentService.VerifySignature(signature, orderId, paymentId);

                    if (IsSignVerified && payment != null)
                    {
                        CartModel cart = TempData.Get<CartModel>("Cart");
                        PaymentDetails model = new PaymentDetails();

                        model.CartId = cart.id;
                        model.Total = cart.Total;
                        model.Tax = cart.Tax;
                        model.GrandTotal = cart.GrandTotal;

                        model.status = payment.Attributes["status"]; //captured
                        model.TransactionId = transactionId;
                        model.Currency = payment.Attributes["currency"];
                        model.Email = payment.Attributes["email"];
                        model.Id = paymentId;
                        model.UserId = CurrentUser.Id;

                        int status = _paymentService.SavePaymentDetails(model);
                        if (status > 0)
                        {
                            Response.Cookies.Append("CId", ""); //resettingg cartId in cookie

                            Address address = TempData.Get<Address>("Address");
                            _orderService.PlaceOrder(CurrentUser.Id, orderId, paymentId, cart, address);

                            //TO DO: Send email
                            TempData.Set("PaymentDetails", model);
                            return RedirectToAction("Receipt");
                        }
                        else
                        {
                            ViewBag.Message = "Although, due to some technical issues it's not get updated in our side. We will contact you soon..";
                        }
                    }
                }
            }
            catch (Exception ex)
            {

            }
            ViewBag.Message = "Your payment has been failed. You can contact us at support@dotnettricks.com.";
            return View();
        }

        public IActionResult Receipt()
        {
            PaymentDetails model = TempData.Peek<PaymentDetails>("PaymentDetails");
            return View(model);
        }
    }
}

ePizzaHub.WebUI/Views/Payment/Index.cshtml
@model PaymentModel
@{
    ViewData["Title"] = "Payment | ePizza Hub";
    Address address = TempData.Peek<Address>("Address");
}
<section>
    @if (Model != null)
    {
        <div class="row mt-3">
            <div class="col-lg-8">
                <div class="card mb-3">
                    <div class="col-sm-12">
                        <h5 class="mt-3">Order Details <span class="float-right"> Item(s): @Model.Cart.Items.Count()</span></h5>
                    </div>
                    <hr />
                    <div class="card-body pt-0 pb-0">
                        @foreach (var item in Model.Cart.Items)
                        {
                            <div class="row">
                                <div class="col-md-5 col-lg-3 col-xl-3">
                                    <div class="rounded mb-3 mb-md-0">
                                        <img class="rounded w-100"
                                             src="@item.ImageUrl" alt="Sample">
                                    </div>
                                </div>
                                <div class="col-md-7 col-lg-9 col-xl-9">
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <h5>@item.Name</h5>
                                            <p class="mb-2 text-muted small">Size: Regular</p>
                                            <p class="mb-2 text-muted small">
                                                Unit Price: ₹@item.UnitPrice.ToString("##.#")
                                            </p>
                                        </div>
                                        <div>
                                            <div class="def-number-input number-input safari_only mb-0 w-100">
                                                <div class="input-group mb-3">
                                                    <input class="form-control sm-control" size="2" min="0" name="quantity" value="@item.Quantity" readonly />
                                                </div>
                                            </div>
                                            <span id="spanTotal" class="form-text text-muted text-center">
                                                Total : ₹@((item.UnitPrice * @item.Quantity).ToString("##.#"))
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @if (Model.Cart.Items.IndexOf(item) < Model.Cart.Items.Count - 1)
                            {
                                <hr class="mb-4">
                            }
                        }
                    </div>
                    <div class="col-sm-12">
                        <h5 class="mt-2">Delivery Address</h5>
                    </div>
                    <hr />
                    <div class="card-body pb-0">
                        <dl class="row">
                            <dt class="col-sm-2">
                                Street
                            </dt>
                            <dd class="col-sm-4">
                                @address.Street
                            </dd>
                            <dt class="col-sm-2">
                                Locality
                            </dt>
                            <dd class="col-sm-4">
                                @address.Locality
                            </dd>
                            <dt class="col-sm-2">
                                Zip Code
                            </dt>
                            <dd class="col-sm-4">
                                @address.ZipCode
                            </dd>
                            <dt class="col-sm-2">
                                Contact No.
                            </dt>
                            <dd class="col-sm-4">
                                @address.PhoneNumber
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card mb-3">
                    <div class="col-sm-12">
                        <h5 class="mt-3">Order Summary</h5>
                    </div>
                    <hr />
                    <div class="card-body pt-0">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                Amount
                                <span>₹@Model.Cart.Total</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                Tax (5%)
                                <span>+₹@Model.Cart.Tax</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center  px-0 mb-3">
                                <strong>Total Amount</strong>
                                <span><strong>₹@Model.Cart.GrandTotal</strong></span>
                            </li>
                        </ul>
                        @if (CurrentUser != null)
                        {
                            <button id="rzp-button" hidden>Pay</button>
                            @using (Html.BeginForm("Status", "Payment", FormMethod.Post, new { id = "PaymentForm", name = "PaymentForm" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Hidden("Receipt", Model.Receipt);
                                @Html.Hidden("Currency", "INR");
                                @Html.Hidden("rzp_signature")
                                @Html.Hidden("rzp_paymentid")
                                @Html.Hidden("rzp_orderid")
                                <button type="submit" id="rzp-paymentresponse" hidden style="display: none;">Submit</button>
                            }
                            <a href="#" class="btn btn-primary btn-block" onclick="submitToPayment()">Pay Now</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</section>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var options = {
        "key": "@Model.RazorpayKey",
        "amount": "@(Model.GrandTotal*100)",
        "currency": "@Model.Currency",
        "name": "@Model.Name",
        "description": "@Model.Description",
       // "image": "https://www.dotnettricks.com/images/d-icon.png",
        "image": "/images/icon.png",
        "order_id": "@Model.OrderId",
        "handler": function (response){
            document.getElementById('rzp_paymentid').value = response.razorpay_payment_id;
            document.getElementById('rzp_orderid').value = response.razorpay_order_id;
            $("#rzp_signature").val(response.razorpay_signature);
            $('#PaymentForm').submit();
        },
        "prefill": {
            "name": "@CurrentUser.Name",
            "email": "@CurrentUser.Email",
            "contact": "@CurrentUser.PhoneNumber"
        },
        "notes": {
            "address": "NA"
        },
        "theme": {
            "color": "#4285F4"
        }
    };
    var rzp = new Razorpay(options);

    window.onload = function(){
        document.getElementById('rzp-button').click();
    };

    document.getElementById('rzp-button').onclick = function (e) {
        rzp.open();
        e.preventDefault();
    };

    function submitToPayment() {
        debugger
       rzp.open();
       e.preventDefault();
    }
</script>

ePizzaHub.WebUI/Views/Payment/Receipt.cshtml
@model ePizzaHub.entities.PaymentDetails

@{
    ViewData["Title"] = "Receipt";
}

<h1>Receipt</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Currency) @Html.DisplayFor(model => model.GrandTotal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model)
        </dt>
        <dd class="col-sm-10">status
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-controller="Order" asp-area="User" class="btn btn-success">Go To Order Details</a>
</div>