ePizzaHub.WebUI/Controllers/HomeController.cs
using ePizzaHub.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ePizzaHub.Services.Interfaces;

namespace ePizzaHub.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        ICatalogService _CatalogService;

        public HomeController(ILogger<HomeController> logger, ICatalogService CatalogService)
        {
            _logger = logger;
            _CatalogService = CatalogService;
        }

        public IActionResult Index()
        {
            var items = _CatalogService.GetItems();
            return View(items);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ePizzaHub.WebUI/ViewComponents/PizzaMenuViewComponent.cs
using ePizzaHub.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ePizzaHub.WebUI.ViewComponents
{
    public class PizzaMenuViewComponent: ViewComponent
    {
        ICatalogService _catalogService;
        public PizzaMenuViewComponent(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        public IViewComponentResult Invoke()
        {
            var items = _catalogService.GetItems();
            return View("~/Views/Shared/_PizzaMenu.cshtml", items);
        }
    }
}

ePizzaHub.WebUI/Views/Home/Index.cshtml
@model IEnumerable<ePizzaHub.entities.Item>
@{
    ViewData["Title"] = "Home Page";
    Layout = "_PublicLayout";
}

<div style="background:#1a5ca3;">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 text-white" style="width:100%">
                <div class="pt-5 pb-5">
                    <h1>ePizza Hub's Online Ordering</h1>
                    <p class="pb-4">
                        Yummy pizza delivered fast at your door step!
                    </p>
                    <p>
                        <a href="#heading" class="btn btn-success">ORDER ONLINE NOW</a>
                    </p>
                </div>
            </div>
            <div class="col-sm-4 pt-4">
                <img src="~/images/pizza-header.png" class="img-fluid" />
            </div>
        </div>
    </div>
</div>

@await Component.InvokeAsync("PizzaMenu");
