ePizzaHub.WebUI/Controllers/CartController.cs
using ePizzaHub.entities;
using ePizzaHub.Repositories.Models;
using ePizzaHub.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using ePizzaHub.WebUI.Helpers;
using ePizzaHub.WebUI.Interfaces;

namespace ePizzaHub.WebUI.Controllers
{
    public class CartController : BaseController
    {
        IcartService _cartService;



        Guid CartId
        {
            get
            {
                Guid Id;
                string Cid = Request.Cookies["CId"];
                if (string.IsNullOrEmpty(Cid))
                {
                    Id = Guid.NewGuid();
                    Response.Cookies.Append("Cid", Id.ToString());
                }
                else
                {
                    Id = Guid.Parse(Cid);
                }
                return Id;

            }
        }
        public CartController(IcartService cartService, IUserAccessor userAccessor) : base(userAccessor)
        {
            _cartService = cartService;
        }
        public IActionResult Index()
        {
            CartModel cart = _cartService.GetCartDetails(CartId);

            if(CurrentUser !=null && cart != null)
            {
                TempData.Set("cart", cart);
                _cartService.UpdateCart(cart.id, CurrentUser.Id);
            }

            return View(cart);
        }

        [Route("Cart/AddToCart/{ItemId}/{UnitPrice}/{Quantity}")]
        public IActionResult AddToCart(int ItemId, decimal UnitPrice, int Quantity)
        {
            int UserId = CurrentUser != null ? CurrentUser.Id : 0;

            if (ItemId > 0 && Quantity > 0)
            {
                Cart cart = _cartService.AddItem(UserId, CartId, ItemId, UnitPrice, Quantity);
                var data = JsonSerializer.Serialize(cart);
                return Json(data);
            }
            else
            {
                return Json("");
            }
        }

        public IActionResult DeleteItem(int Id)
        {
            int count = _cartService.DeleteItem(CartId, Id);
            return Json(count);
        }

        [Route("Cart/UpdateQuantity/{Id}/{Quantity}")]
        public IActionResult UpdateQuantity(int Id, int Quantity)
        {
            int count = _cartService.UpdateQuantity(CartId, Id, Quantity);
            return Json(count);
        }

        public IActionResult GetCartCount()
        {
            int count = _cartService.GetCartCount(CartId);
            return Json(count);
        }

        public IActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckOut(Address address)
        {
            TempData.Set("Address", address);
            return RedirectToAction("Index", "Payment");
        }

    }
}

ePizzaHub.WebUI/Views/Cart/CheckOut.cshtml
@model ePizzaHub.entities.Address

@{
    ViewData["Title"] = "CheckOut";
}

 

<h4>CheckOut Address</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CheckOut">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Locality" class="control-label"></label>
                <input asp-for="Locality" class="form-control" />
                <span asp-validation-for="Locality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Continue" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


ePizzaHub.WebUI/Views/Cart/Index.cshtml
@model ePizzaHub.Repositories.Models.CartModel
<section>
    @if (Model != null && Model.Items.Count > 0)
    {
        <div class="row mt-3">
            <div class="col-lg-8">
                <div class="card mb-3">
                    <div class="col-sm-12">
                        <h5 class="mt-3">Cart (@Model.Items.Count() Items)</h5>
                    </div>
                    <hr />
                    <div class="card-body pt-0 pb-0">
                        @foreach (var item in Model.Items)
                        {
                            <div class="row">
                                <div class="col-md-5 col-lg-3 col-xl-3">
                                    <div class="rounded mb-3 mb-md-0">
                                        <img class="rounded w-100"
                                             src="@item.ImageUrl" alt="Sample">
                                    </div>
                                </div>
                                <div class="col-md-7 col-lg-9 col-xl-9">
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <h5>@item.Name</h5>
                                            <p class="mb-2 text-muted small">Size: Regular</p>
                                            <p class="mb-2 text-muted small">
                                                Unit Price: ₹@item.UnitPrice.ToString("##.#")
                                                <span class="pl-1">
                                                    <a href="javascript:void(0)" onclick="deleteItem('@item.Id')" title="Remove" class="pt-0"><i class="bi bi-trash text-danger"></i></a>
                                                </span>
                                            </p>
                                        </div>
                                        <div>
                                            <div class="def-number-input number-input safari_only mb-0 w-100">
                                                <div class="input-group mb-3">
                                                    <div class="input-group-prepend">
                                                        <button onclick="updateQuantity('@item.Id',-1)" class="btn btn-outline-secondary" type="button">-</button>
                                                    </div>
                                                    <input class="form-control sm-control" size="2" min="0" name="quantity" value="@item.Quantity" readonly />
                                                    <div class="input-group-append">
                                                        <button onclick="updateQuantity('@item.Id',1)" class="btn btn-outline-secondary" type="button">+</button>
                                                    </div>
                                                </div>
                                            </div>
                                            <span id="spanTotal" class="form-text text-muted text-center">
                                                Total : ₹@((item.UnitPrice * @item.Quantity).ToString("##.#"))
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @if (Model.Items.IndexOf(item) < Model.Items.Count - 1)
                            {
                                <hr class="mb-4">
                            }
                        }
                    </div>
                </div>
                <div class="mb-3">
                    <a href="/" class="btn btn-outline-primary">Continue Shopping</a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card mb-3">
                    <div class="col-sm-12">
                        <h5 class="mt-3">Order Summary</h5>
                    </div>
                    <hr />
                    <div class="card-body pt-0">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                Amount
                                <span>₹@Model.Total</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                Tax (5%)
                                <span>+₹@Model.Tax</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center  px-0 mb-3">
                                <strong>Total Amount</strong>
                                <span><strong>₹@Model.GrandTotal</strong></span>
                            </li>
                        </ul>
                        @if (CurrentUser != null)
                        {
                            <a asp-action="Checkout" asp-controller="Cart" class="btn btn-success btn-block">Checkout</a>
                        }
                        else
                        {
                            <a asp-action="Login" asp-controller="Account" class="btn btn-primary btn-block"
                               asp-route-returnurl="/Cart/Index">Checkout</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-sm-12 mt-5">
                <p style="min-height:300px">
                    Your cart is empty. Please add some items from the menu.! <br><br>
                    <a href="/" class="btn btn-primary">Browse Menu</a>
                </p>
            </div>
        </div>
    }
</section>